name: Node.js Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: User Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'
      - run: cd server
<<<<<<< HEAD
=======
      - run: npm init -y
>>>>>>> 5c9d61a72c6817e0683322cb6353c52e43ac9cba
      - run: npm install
      - run: npm run test
          
